import { useEffect, useState } from 'react';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import axios from "axios";

export default function Home() {

  const [cardData, setCardData] = useState([])

  useEffect(() => {
    const testURL = 'https://combonation.in/mobile/api/categories';
    const myInit = {
      method: 'GET',
      mode: 'no-cors',
      headers: {
        'Content-Type': 'application/json'
      },
    };

    const myRequest = new Request(testURL, myInit);

    fetch(myRequest)
      .then(r => r.json().then(data => { setCardData(data) }))
      .then(obj => console.log(obj));
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {cardData?.map((val, indx) => {
            return (
              <div key={indx} className="card m-2" style={{ width: "18rem" }}>
                <img
                  src={val?.banner?.banner}
                  className="card-img-top"
                  alt={val?.name}
                  width="200"
                  height="200" />
                <div className="card-body">
                  <p className="card-text">{val?.name}</p>
                </div>
              </div>
            )
          })}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
